/**
 * Copyright (c) Ladifire, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

export const themeDataCustom = {
  "lf-active-icon": "black",
  "lf-attachment-footer-background": "black",
  "lf-black": "black",
  "lf-black-alpha-05": "rgba(0, 0, 0, 0.05)",
  "lf-black-alpha-10": "rgba(0, 0, 0, 0.1)",
  "lf-black-alpha-15": "rgba(0, 0, 0, 0.15)",
  "lf-black-alpha-20": "rgba(0, 0, 0, 0.2)",
  "lf-black-alpha-30": "rgba(0, 0, 0, 0.3)",
  "lf-black-alpha-40": "rgba(0, 0, 0, 0.4)",
  "lf-black-alpha-50": "rgba(0, 0, 0, 0.5)",
  "lf-black-alpha-60": "rgba(0, 0, 0, 0.6)",
  "lf-black-alpha-80": "rgba(0, 0, 0, 0.8)",
  "lf-blue-05": "black",
  "lf-blue-30": "black",
  "lf-blue-40": "black",
  "lf-blue-60": "black",
  "lf-blue-70": "black",
  "lf-blue-80": "black",
  "lf-blue-95": "black",
  "lf-blue-badge": "black",
  "lf-blue-link": "black",
  "lf-button-icon": "black",
  "lf-button-text": "black",
  "lf-comment-background": "black",
  "lf-dark-mode-gray-35": "black",
  "lf-dark-mode-gray-50": "black",
  "lf-dark-mode-gray-70": "black",
  "lf-dark-mode-gray-80": "black",
  "lf-dark-mode-gray-90": "black",
  "lf-dark-mode-gray-100": "black",
  "lf-dark-ui-card-border": "black",
  "lf-dark-ui-cards": "black",
  "lf-dark-ui-disabled-icon": "black",
  "lf-dark-ui-divider": "black",
  "lf-dark-ui-medium-text": "black",
  "lf-dark-ui-nav-bar": "black",
  "lf-dark-ui-primary-icon": "black",
  "lf-dark-ui-primary-text": "black",
  "lf-dark-ui-secondary-icon": "black",
  "lf-dark-ui-secondary-text": "black",
  "lf-dark-ui-tab-bar": "black",
  "lf-dark-ui-wash": "black",
  "lf-data-mango": "black",
  "lf-disabled-icon": "black",
  "lf-disabled-text": "black",
  "lf-divider-on-wash": "black",
  "lf-divider-on-white": "black",
  "lf-fast": "200ms",
  "lf-fb-blue-70": "black",
  "lf-fb-blue-75": "black",
  "lf-gray-00": "black",
  "lf-gray-05": "black",
  "lf-gray-10": "black",
  "lf-gray-20": "black",
  "lf-gray-25": "black",
  "lf-gray-30": "black",
  "lf-gray-45": "black",
  "lf-gray-70": "black",
  "lf-gray-80": "black",
  "lf-gray-90": "black",
  "lf-gray-100": "black",
  "lf-green-30": "black",
  "lf-green-55": "black",
  "lf-green-60": "black",
  "lf-green-70": "black",
  "lf-highlight": "black",
  "lf-highlight-cell-background": "black",
  "lf-list-cell-pressed": "black",
  "lf-mobile-wash": "black",
  "lf-nav-bar-background": "black",
  "lf-negative": "black",
  "lf-notification-badge": "black",
  "lf-placeholder-text": "black",
  "lf-positive": "black",
  "lf-primary-button-pressed": "black",
  "lf-primary-icon": "white",
  "lf-primary-text": "white",
  "lf-red-55": "black",
  "lf-secondary-button-pressed": "black",
  "lf-secondary-icon": "black",
  "lf-secondary-text": "black",
  "lf-slow": "400ms",
  "lf-soft": "cubic-bezier(.08,.52,.52,1)",
  "lf-spectrum-aluminum": "black",
  "lf-spectrum-aluminum-dark-1": "black",
  "lf-spectrum-aluminum-dark-2": "black",
  "lf-spectrum-aluminum-dark-3": "black",
  "lf-spectrum-aluminum-tint-15": "black",
  "lf-spectrum-aluminum-tint-30": "black",
  "lf-spectrum-aluminum-tint-50": "black",
  "lf-spectrum-aluminum-tint-70": "black",
  "lf-spectrum-aluminum-tint-90": "black",
  "lf-spectrum-blue-gray": "black",
  "lf-spectrum-blue-gray-dark-1": "black",
  "lf-spectrum-blue-gray-dark-2": "black",
  "lf-spectrum-blue-gray-dark-3": "black",
  "lf-spectrum-blue-gray-tint-15": "black",
  "lf-spectrum-blue-gray-tint-30": "black",
  "lf-spectrum-blue-gray-tint-50": "black",
  "lf-spectrum-blue-gray-tint-70": "black",
  "lf-spectrum-blue-gray-tint-90": "black",
  "lf-spectrum-cherry": "black",
  "lf-spectrum-cherry-dark-1": "black",
  "lf-spectrum-cherry-dark-2": "black",
  "lf-spectrum-cherry-dark-3": "black",
  "lf-spectrum-cherry-tint-15": "black",
  "lf-spectrum-cherry-tint-30": "black",
  "lf-spectrum-cherry-tint-50": "black",
  "lf-spectrum-cherry-tint-70": "black",
  "lf-spectrum-cherry-tint-90": "black",
  "lf-spectrum-grape": "black",
  "lf-spectrum-grape-dark-1": "black",
  "lf-spectrum-grape-dark-2": "black",
  "lf-spectrum-grape-dark-3": "black",
  "lf-spectrum-grape-tint-15": "black",
  "lf-spectrum-grape-tint-30": "black",
  "lf-spectrum-grape-tint-50": "black",
  "lf-spectrum-grape-tint-70": "black",
  "lf-spectrum-grape-tint-90": "black",
  "lf-spectrum-lemon": "black",
  "lf-spectrum-lemon-dark-1": "black",
  "lf-spectrum-lemon-dark-2": "black",
  "lf-spectrum-lemon-dark-3": "black",
  "lf-spectrum-lemon-tint-15": "black",
  "lf-spectrum-lemon-tint-30": "black",
  "lf-spectrum-lemon-tint-50": "black",
  "lf-spectrum-lemon-tint-70": "black",
  "lf-spectrum-lemon-tint-90": "black",
  "lf-spectrum-lime": "black",
  "lf-spectrum-lime-dark-1": "black",
  "lf-spectrum-lime-dark-2": "black",
  "lf-spectrum-lime-dark-3": "black",
  "lf-spectrum-lime-tint-15": "black",
  "lf-spectrum-lime-tint-30": "black",
  "lf-spectrum-lime-tint-50": "black",
  "lf-spectrum-lime-tint-70": "black",
  "lf-spectrum-lime-tint-90": "black",
  "lf-spectrum-orange": "black",
  "lf-spectrum-orange-dark-1": "black",
  "lf-spectrum-orange-dark-2": "black",
  "lf-spectrum-orange-dark-3": "black",
  "lf-spectrum-orange-tint-15": "black",
  "lf-spectrum-orange-tint-30": "black",
  "lf-spectrum-orange-tint-50": "black",
  "lf-spectrum-orange-tint-70": "black",
  "lf-spectrum-orange-tint-90": "black",
  "lf-spectrum-pink": "black",
  "lf-spectrum-pink-dark-1": "black",
  "lf-spectrum-pink-dark-2": "black",
  "lf-spectrum-pink-dark-3": "black",
  "lf-spectrum-pink-tint-15": "black",
  "lf-spectrum-pink-tint-30": "black",
  "lf-spectrum-pink-tint-50": "black",
  "lf-spectrum-pink-tint-70": "black",
  "lf-spectrum-pink-tint-90": "black",
  "lf-spectrum-seafoam": "black",
  "lf-spectrum-seafoam-dark-1": "black",
  "lf-spectrum-seafoam-dark-2": "black",
  "lf-spectrum-seafoam-dark-3": "black",
  "lf-spectrum-seafoam-tint-15": "black",
  "lf-spectrum-seafoam-tint-30": "black",
  "lf-spectrum-seafoam-tint-50": "black",
  "lf-spectrum-seafoam-tint-70": "black",
  "lf-spectrum-seafoam-tint-90": "black",
  "lf-spectrum-skin-1": "black",
  "lf-spectrum-skin-1-dark-1": "black",
  "lf-spectrum-skin-1-dark-2": "black",
  "lf-spectrum-skin-1-dark-3": "black",
  "lf-spectrum-skin-1-tint-15": "black",
  "lf-spectrum-skin-1-tint-30": "black",
  "lf-spectrum-skin-1-tint-50": "black",
  "lf-spectrum-skin-1-tint-70": "black",
  "lf-spectrum-skin-1-tint-90": "black",
  "lf-spectrum-skin-2": "black",
  "lf-spectrum-skin-2-dark-1": "black",
  "lf-spectrum-skin-2-dark-2": "black",
  "lf-spectrum-skin-2-dark-3": "black",
  "lf-spectrum-skin-2-tint-15": "black",
  "lf-spectrum-skin-2-tint-30": "black",
  "lf-spectrum-skin-2-tint-50": "black",
  "lf-spectrum-skin-2-tint-70": "black",
  "lf-spectrum-skin-2-tint-90": "black",
  "lf-spectrum-skin-3": "black",
  "lf-spectrum-skin-3-dark-1": "black",
  "lf-spectrum-skin-3-dark-2": "black",
  "lf-spectrum-skin-3-dark-3": "black",
  "lf-spectrum-skin-3-tint-15": "black",
  "lf-spectrum-skin-3-tint-30": "black",
  "lf-spectrum-skin-3-tint-50": "black",
  "lf-spectrum-skin-3-tint-70": "black",
  "lf-spectrum-skin-3-tint-90": "black",
  "lf-spectrum-skin-4": "black",
  "lf-spectrum-skin-4-dark-1": "black",
  "lf-spectrum-skin-4-dark-2": "black",
  "lf-spectrum-skin-4-dark-3": "black",
  "lf-spectrum-skin-4-tint-15": "black",
  "lf-spectrum-skin-4-tint-30": "black",
  "lf-spectrum-skin-4-tint-50": "black",
  "lf-spectrum-skin-4-tint-70": "black",
  "lf-spectrum-skin-4-tint-90": "black",
  "lf-spectrum-skin-5": "black",
  "lf-spectrum-skin-5-dark-1": "black",
  "lf-spectrum-skin-5-dark-2": "black",
  "lf-spectrum-skin-5-dark-3": "black",
  "lf-spectrum-skin-5-tint-15": "black",
  "lf-spectrum-skin-5-tint-30": "black",
  "lf-spectrum-skin-5-tint-50": "black",
  "lf-spectrum-skin-5-tint-70": "black",
  "lf-spectrum-skin-5-tint-90": "black",
  "lf-spectrum-slate": "black",
  "lf-spectrum-slate-dark-1": "black",
  "lf-spectrum-slate-dark-2": "black",
  "lf-spectrum-slate-dark-3": "black",
  "lf-spectrum-slate-tint-15": "black",
  "lf-spectrum-slate-tint-30": "black",
  "lf-spectrum-slate-tint-50": "black",
  "lf-spectrum-slate-tint-70": "black",
  "lf-spectrum-slate-tint-90": "black",
  "lf-spectrum-teal": "black",
  "lf-spectrum-teal-dark-1": "black",
  "lf-spectrum-teal-dark-2": "black",
  "lf-spectrum-teal-dark-3": "black",
  "lf-spectrum-teal-tint-15": "black",
  "lf-spectrum-teal-tint-30": "black",
  "lf-spectrum-teal-tint-50": "black",
  "lf-spectrum-teal-tint-70": "black",
  "lf-spectrum-teal-tint-90": "black",
  "lf-spectrum-tomato": "black",
  "lf-spectrum-tomato-dark-1": "black",
  "lf-spectrum-tomato-dark-2": "black",
  "lf-spectrum-tomato-dark-3": "black",
  "lf-spectrum-tomato-tint-15": "black",
  "lf-spectrum-tomato-tint-30": "black",
  "lf-spectrum-tomato-tint-50": "black",
  "lf-spectrum-tomato-tint-70": "black",
  "lf-spectrum-tomato-tint-90": "black",
  "lf-strong": "cubic-bezier(.12,.8,.32,1)",
  "lf-tertiary-icon": "black",
  "lf-white": "black",
  "lf-white-alpha-05": "rgba(255, 255, 255, 0.05)",
  "lf-white-alpha-10": "rgba(255, 255, 255, 0.1)",
  "lf-white-alpha-15": "rgba(255, 255, 255, 0.15)",
  "lf-white-alpha-20": "rgba(255, 255, 255, 0.2)",
  "lf-white-alpha-30": "rgba(255, 255, 255, 0.3)",
  "lf-white-alpha-40": "rgba(255, 255, 255, 0.4)",
  "lf-white-alpha-50": "rgba(255, 255, 255, 0.5)",
  "lf-white-alpha-60": "rgba(255, 255, 255, 0.6)",
  "lf-white-alpha-80": "rgba(255, 255, 255, 0.8)",
  "lf-white-text": "black",
  "lf-www-wash": "black",
  "lf-yellow-20": "black",
  "header-height": "60px",
  "lf-animation-enter-exit-in": "cubic-bezier(0.14, 1, 0.34, 1)",
  "lf-animation-enter-exit-out": "cubic-bezier(0.45, 0.1, 0.2, 1)",
  "lf-animation-swap-shuffle-in": "cubic-bezier(0.14, 1, 0.34, 1)",
  "lf-animation-swap-shuffle-out": "cubic-bezier(0.45, 0.1, 0.2, 1)",
  "lf-animation-move-in": "cubic-bezier(0.17, 0.17, 0, 1)",
  "lf-animation-move-out": "cubic-bezier(0.17, 0.17, 0, 1)",
  "lf-animation-expand-collapse-in": "cubic-bezier(0.17, 0.17, 0, 1)",
  "lf-animation-expand-collapse-out": "cubic-bezier(0.17, 0.17, 0, 1)",
  "lf-animation-passive-move-in": "cubic-bezier(0.5, 0, 0.1, 1)",
  "lf-animation-passive-move-out": "cubic-bezier(0.5, 0, 0.1, 1)",
  "lf-animation-quick-move-in": "cubic-bezier(0.1, 0.9, 0.2, 1)",
  "lf-animation-quick-move-out": "cubic-bezier(0.1, 0.9, 0.2, 1)",
  "lf-animation-fade-in": "cubic-bezier(0, 0, 1, 1)",
  "lf-animation-fade-out": "cubic-bezier(0, 0, 1, 1)",
  "lf-duration-extra-extra-short-in": "100ms",
  "lf-duration-extra-extra-short-out": "100ms",
  "lf-duration-extra-short-in": "200ms",
  "lf-duration-extra-short-out": "150ms",
  "lf-duration-short-in": "280ms",
  "lf-duration-short-out": "200ms",
  "lf-duration-medium-in": "400ms",
  "lf-duration-medium-out": "350ms",
  "lf-duration-long-in": "500ms",
  "lf-duration-long-out": "350ms",
  "lf-duration-extra-long-in": "1000ms",
  "lf-duration-extra-long-out": "1000ms",
  "lf-duration-none": "0ms",
  accent: "rgb(29,161,242)",
  "always-white": "white",
  "always-black": "black",
  "always-dark-gradient": "linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0.6))",
  "always-dark-overlay": "rgba(0, 0, 0, 0.4)",
  "always-light-overlay": "rgba(255, 255, 255, 0.4)",
  "always-gray-40": "#65676B",
  "always-gray-75": "#BCC0C4",
  "always-gray-95": "#F0F2F5",
  "attachment-footer-background": "rgba(255,255,255,0.1)",
  "base-blue": "#1877F2",
  "base-cherry": "#F3425F",
  "base-grape": "#9360F7",
  "base-lemon": "#F7B928",
  "base-lime": "#45BD62",
  "base-pink": "#FF66BF",
  "base-seafoam": "#54C7EC",
  "base-teal": "#2ABBA7",
  "base-tomato": "#FB724B",
  "blue-link": "#4599FF",
  "card-background": "#242526",
  "card-background-flat": "#323436",
  "comment-background": "#3A3B3C",
  "comment-footer-background": "#4E4F50",
  "dataviz-primary-1": "rgb(48,200,180)",
  "disabled-button-background": "rgba(255, 255, 255, 0.2)",
  "disabled-icon": "rgba(255, 255, 255, 0.3)",
  "disabled-text": "rgba(255, 255, 255, 0.3)",
  divider: "#3E4042",
  "event-date": "#F3425F",
  "filter-accent": "invert(40%) sepia(52%) saturate(200%) saturate(200%) saturate(200%) saturate(189%) hue-rotate(191deg) brightness(103%) contrast(102%)",
  "filter-always-white": "invert(100%)",
  "filter-disabled-icon": "invert(100%) opacity(30%)",
  "filter-placeholder-icon": "invert(59%) sepia(11%) saturate(200%) saturate(135%) hue-rotate(176deg) brightness(96%) contrast(94%)",
  "filter-primary-icon": "invert(100%)",
  "filter-secondary-icon": "invert(62%) sepia(98%) saturate(12%) hue-rotate(175deg) brightness(90%) contrast(96%)",
  "filter-warning-icon": "invert(77%) sepia(29%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(128%) hue-rotate(359deg) brightness(102%) contrast(107%)",
  "filter-blue-link-icon": "invert(73%) sepia(29%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(103.25%) hue-rotate(189deg) brightness(101%) contrast(101%)",
  "filter-positive": "invert(37%) sepia(61%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(115%) hue-rotate(91deg) brightness(97%) contrast(105%)",
  "filter-negative": "invert(25%) sepia(33%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(110%) hue-rotate(345deg) brightness(132%) contrast(96%)",
  "font-family-apple": "system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif",
  "font-family-default": "Helvetica, Arial, sans-serif",
  "font-family-segoe": "Segoe UI Historic, Segoe UI, Helvetica, Arial, sans-serif",
  "glimmer-spinner-icon": "white",
  "hero-banner-background": "#E85D07",
  "hosted-view-selected-state": "rgba(45, 136, 255, 0.2)",
  "highlight-bg": "rgba(24, 119, 242, .31)",
  "hover-overlay": "rgba(29, 161, 242, 0.1)",
  "media-hover": "rgba(68, 73, 80, 0.15)",
  "media-inner-border": "rgba(255, 255, 255, 0.05)",
  "media-outer-border": "#33363A",
  "media-pressed": "rgba(68, 73, 80, 0.35)",
  "messenger-card-background": "#242526",
  "messenger-reply-background": "#18191A",
  "overlay-alpha-80": "rgba(11, 11, 11, 0.8)",
  "overlay-on-media": "rgba(0, 0, 0, 0.6)",
  "nav-bar-background": "#242526",
  "nav-bar-background-gradient": "linear-gradient(to top, #242526, rgba(36,37,38,.9), rgba(36,37,38,.7), rgba(36,37,38,.4), rgba(36,37,38,0))",
  "nav-bar-background-gradient-wash": "linear-gradient(to top, #18191A, rgba(24,25,26,.9), rgba(24,25,26,.7), rgba(24,25,26,.4), rgba(24,25,26,0))",
  negative: "rgb(224, 36, 94)",
  "negative-background": "hsl(350, 87%, 55%, 20%)",
  "new-notification-background": "#E7F3FF",
  "non-media-pressed": "rgba(29, 161, 242, 0.15)",
  "non-media-pressed-on-dark": "rgba(255, 255, 255, 0.3)",
  "notification-badge": "rgb(224, 36, 94)",
  "placeholder-icon": "#8A8D91",
  "placeholder-text": "#8A8D91",
  "placeholder-text-on-media": "rgba(255, 255, 255, 0.5)",
  "popover-background": "#3E4042",
  positive: "#31A24C",
  "positive-background": "#1F3520",
  "press-overlay": "rgba(29, 161, 242, 0.2)",
  "primary-button-background": "#2D88FF",
  "primary-button-background-experiment": "#2374E1",
  "primary-button-pressed": "#77A7FF",
  "primary-button-text": "#FFFFFF",
  "primary-deemphasized-button-background": "rgba(45, 136, 255, 0.2)",
  "primary-deemphasized-button-pressed": "rgba(24, 119, 242, 0.2)",
  "primary-deemphasized-button-pressed-overlay": "rgba(25, 110, 255, 0.15)",
  "primary-deemphasized-button-text": "#2D88FF",
  "primary-icon": "#E4E6EB",
  "primary-text": "#E4E6EB",
  "primary-text-on-media": "white",
  "progress-ring-neutral-background": "rgba(255, 255, 255, 0.2)",
  "progress-ring-neutral-foreground": "#ffffff",
  "progress-ring-on-media-background": "rgba(255, 255, 255, 0.2)",
  "progress-ring-on-media-foreground": "#FFFFFF",
  "progress-ring-blue-background": "rgba(45, 136, 255, 0.2)",
  "progress-ring-blue-foreground": "hsl(214, 100%, 59%)",
  "progress-ring-disabled-background": "rgba(122,125,130, 0.2)",
  "progress-ring-disabled-foreground": "#7A7D82",
  "scroll-thumb": "rgba(255, 255, 255, 0.3)",
  "secondary-button-background": "rgba(255,255,255,.1)",
  "secondary-button-background-floating": "#4B4C4F",
  "secondary-button-background-on-dark": "rgba(255, 255, 255, 0.4)",
  "secondary-button-pressed": "rgba(0, 0, 0, 0.05)",
  "secondary-button-text": "#E4E6EB",
  "secondary-icon": "#B0B3B8",
  "secondary-text": "#B0B3B8",
  "secondary-text-on-media": "rgba(255, 255, 255, 0.9)",
  "section-header-text": "#BCC0C4",
  "shadow-1": "rgba(0, 0, 0, 0.1)",
  "shadow-2": "rgba(0, 0, 0, 0.2)",
  "shadow-5": "rgba(0, 0, 0, 0.5)",
  "shadow-8": "rgba(0, 0, 0, 0.8)",
  "shadow-inset": "rgba(255, 255, 255, 0.05)",
  "surface-background": "#242526",
  "text-highlight": "rgba(24, 119, 242, 0.45)",
  "toggle-active-background": "rgb(45, 136, 255)",
  "toggle-active-icon": "#FFFFFF",
  "toggle-active-text": "#FFFFFF",
  "toggle-button-active-background": "#E6F2FF",
  wash: "#3E4042",
  "web-wash": "#18191A",
  warning: "hsl(40, 89%, 52%)",
  "dataviz-primary-2": "rgb(134,218,255)",
  "dataviz-primary-3": "rgb(95,170,255)",
  "dataviz-secondary-1": "rgb(129,77,231)",
  "dataviz-secondary-2": "rgb(168,124,255)",
  "dataviz-secondary-3": "rgb(219,26,139)",
  "dataviz-supplementary-1": "rgb(255,122,105)",
  "dataviz-supplementary-2": "rgb(241,168,23)",
  "dataviz-supplementary-3": "rgb(49,162,76)",
  "dataviz-supplementary-4": "rgb(228,230,235)"
};
